package mutual.model.enums;

public enum CustomerRequestType {

    GET_AVAILABLE_ROOMS,
    GET_HOTEL_DETAILS,
    NEW_RESERVATION,
    LOAD_RESERVATION_BY_ID,
    LOAD_RESERVATION_BY_EMAIL,
    MODIFY_RESERVATION,
    GET_PRICE_FOR_EXTRA_NIGHTS
}
