package mutual.model.enums;

public enum HotelPropertyModificationType {
    UPDATE_NAME,
    UPDATE_DESCRIPTION,
    UPDATE_PHONE_NUMBER,
    UPDATE_CHECK_IN_AGE,
    UPDATE_CHECK_OUT_TIME,
    UPDATE_CHECK_IN_TIME,
    UPDATE_AMENITIES,
    UPDATE_OPERATING_HOURS,
    REMOVE_ROOM_CATEGORY,
    ADD_ROOM_CATEGORY,
    UPDATE_ROOM_CATEGORY
}
