package mutual.model.enums;

public enum ManagementRequestType {
    ATTEMPT_SIGN_IN,
    CREATE_NEW_ACCOUNT,
    DELETE_HOTEL,
    GET_UPCOMING_CHECK_INS,
    GENERIC_AVAILABILITY_QUERY,
    NEW_RESERVATION,
    UPDATE_HOTEL_DETAILS,
    GET_ROOM_CATEGORIES,
    RESERVATION_SEARCH,
    NEW_HOTEL,
    CATEGORY_SPECIFIC_AVAILABILITY_QUERY,
    MODIFY_AVAILABILITY
}
